function [matrix, vector] = getdata1(size)
    matrix = 7 .* eye(size) ...
        + 3 .* [zeros(1, size); eye(size - 1), zeros(size - 1, 1)] ...
        + 3 .* [zeros(size - 1, 1), eye(size - 1); zeros(1, size)];

    vector = 5 * ones(size, 1) ...
        + 0.2 .* ones(size, 1) .* (1:size)';
end
