function [] = writedata(solver, degree, timeStr, row, a, approxErr, solverErr, solverCond)
    outfile_suffix = strcat( ...
        '_' , timeStr, ...
        '.xlsx');

    writecell(cat(2, {"solver", "degree"}, cellfun(@(x) ['a_', num2str(x)], num2cell(0:degree), "UniformOutput", false)), ...
        strcat('a', outfile_suffix), ...
        "Range", ['A1', ':', index2column(degree + 3), '1']);
    writecell(cat(2, {functions(solver).function, num2str(degree)}, preparenums(a')), ...
        strcat('a', outfile_suffix), ...
        "Range", ['A', num2str(row), ':', index2column(degree + 3), num2str(row)]);

    writecell({"solver", "degree", "approximation error"}, ...
        strcat('approxErr', outfile_suffix), ...
        "Range", ['A1', ':', index2column(3), '1']);
    writecell({functions(solver).function, num2str(degree), num2str(approxErr)}, ...
        strcat('approxErr', outfile_suffix), ...
        "Range", ['A', num2str(row), ':', index2column(3), num2str(row)]);

    writecell({"solver", "degree", "solution error"}, ...
        strcat('solverErr', outfile_suffix), ...
        "Range", ['A1', ':', index2column(3), '1']);
    writecell({functions(solver).function, num2str(degree), num2str(solverErr)}, ...
        strcat('solverErr', outfile_suffix), ...
        "Range", ['A', num2str(row), ':', index2column(3), num2str(row)]);

    writecell({"solver", "degree", "solverCond"}, ...
        strcat('solverCond', outfile_suffix), ...
        "Range", ['A1', ':', index2column(3), '1']);
    writecell({functions(solver).function, num2str(degree), num2str(solverCond)}, ...
        strcat('solverCond', outfile_suffix), ...
        "Range", ['A', num2str(row), ':', index2column(3), num2str(row)]);
end

function out = preparenums(mat)
    out = cellfun(@num2str, num2cell(mat), 'UniformOutput', false);
end

function out = index2column(index)
    out = '';
    index = index - 1;
    while index > 0
        letter = char(65 + mod(index, 26));
        out = [letter, out];
        index = fix(index / 26);
    end
end
